### ISSUE TITLE
High CPU usage for heapster v0.6

### ISSUE THREAD

**Issue by antmanler** [GoogleCloudPlatform/heapster#77]
I updated to latest version of heapster(kubernetes/heapster:v0.6) and influxdb(kubernetes/heapster_influxdb:v0.3) and found high CPU usage of influxdb.

I downgrade to heapster_influxdb:v0.2, still got high load, then tried heapster:v0.5, the cpu loads seemed normal

**heapter v0.5 + heapster_influxdb:v0.3**:
![v0 5](https://cloud.githubusercontent.com/assets/354668/5959700/4d975b08-a80b-11e4-84d0-b2d588efad2b.png)

**heapter v0.6 + heapster_influxdb:v0.3**:
![v0 6](https://cloud.githubusercontent.com/assets/354668/5959702/50b53634-a80b-11e4-980c-a519e3456c78.png)

**Comment by vishh** [comment]
Thanks for reporting the issue. I will probe further on the CPU usage part.
Meanwhile, it is possible to cap the total amount of CPU and memory that
InfluxDB consumes. That might reduce the responsiveness of InfluxDB. Is
that an acceptable solution?

**Comment by antmanler** [comment]
I think it's better to make trade off, since a monitoring service should not cost much computing resources in cluster.
And I've no idea why sending data to influxdb will cause so much CPU usage, I checked the network payload in influxdb's container and there is not a lot of data incomes every 10 sec. I wonder maybe this issue is related to influxdb itself or its golang client?

**Comment by vishh** [comment]
I agree with your assessment. I have seen InfluxDB use up all the CPU it
can at times. I will send out a PR to limit resource usage for the
monitoring infrastructure in general.

**Comment by vishh** [comment]
@antmanler: We are working on separating heapster from InfluxDB and Grafana. Heapster by itself should use minimal CPU and we will place appropriate resource restrictions to enforce that.

For InfluxDB though, its performance becomes abysmal when we restrict it to less than 1 CPU. Since the current default cluster config in kubernetes uses 1 cpu GCE VMs, setting InfluxDBs CPU limit to '1' will consume an entire node. So I think the idea would be for users to place appropriate resource restrictions for InfluxDB.

**Comment by vishh** [comment]
Let me know if you need any help placing CPU and Memory restrictions on InfluxDB.

**Comment by antmanler** [comment]
Thanks, sorry so busy these days, I'll try to put restrictions on InfluxDB and tune its resources consumption

**Comment by vishh** [comment]
Closing this issue.
